version: '3'

services:
  server:
    image: marie/flaskserver:0.0.0
    build: ./server
    command: python server.py
    ports:
      - 8484:5151
  client:
    image: marie/flaskclient:0.0.0
    build: ./client
    command: python client.py
    network_mode: host
    depends_on:
      - server